import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProviderWrapper } from "./sessionWrapper";
import { Navbar } from "@nextui-org/react";
import { MySessionProvider } from "./contexts/session";
import CourseProviderWrapper from "./contexts/course/wrapper";
import ProfProviderWrapper from "./contexts/prof/wrapper";
import { SessionProvider } from "next-auth/react";
import ProfileProviderWrapper from "./contexts/profile/wrapper";
import DegreeProgramProviderWrapper from "./contexts/degree-programs/wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * React context is UNAVAILABLE in server level components (this is server level).
 * Therefore call a helper component which isn't itself a context, but which helps us 
 * retrieve a context.
 * @param param0 
 * @returns 
 */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <CourseProviderWrapper>
          <ProfProviderWrapper>
            <SessionProviderWrapper>
              <ProfileProviderWrapper>
                <DegreeProgramProviderWrapper>
                  {children}
                </DegreeProgramProviderWrapper>
              </ProfileProviderWrapper>
            </SessionProviderWrapper>
          </ProfProviderWrapper>
        </CourseProviderWrapper>
      </body>
    </html>
  );
}
