import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CourseProviderWrapper from "./server-contexts/course/wrapper";
import ProfProviderWrapper from "./server-contexts/prof/wrapper";
import { SessionProviderWrapper } from "./sessionWrapper";
import ProfileProviderWrapper from "./server-contexts/profile/wrapper";
import DegreeProgramProviderWrapper from "./server-contexts/degree-programs/wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * React context is UNAVAILABLE in server level components (this is server level).
 * Therefore call a helper component which isn't itself a context, but which helps us 
 * retrieve a context.
 * @param param0 
 * @returns 
 */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/** For latex */}
        <link
          href="//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css"
          rel="stylesheet"
        />
      </head>
      <body className={`${inter.className}`}>
        <CourseProviderWrapper>
          <ProfProviderWrapper>
            <SessionProviderWrapper>
              <ProfileProviderWrapper>
                <DegreeProgramProviderWrapper>
                  {children}
                </DegreeProgramProviderWrapper>
              </ProfileProviderWrapper>
            </SessionProviderWrapper>
          </ProfProviderWrapper>
        </CourseProviderWrapper>
      </body>
    </html>
  );
}
