import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CourseProviderWrapper from "./contexts/server/course/wrapper";
import ProfProviderWrapper from "./contexts/server/prof/wrapper";
import { SessionProviderWrapper } from "./sessionWrapper";
import DegreeProgramProviderWrapper from "./contexts/server/degree-programs/wrapper";
import DatabaseProfileProviderWrapper from "./contexts/server/profile/wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * React context is UNAVAILABLE in server level components (this is server level).
 * Therefore call a helper component which isn't itself a context, but which helps us 
 * retrieve a context.
 * @param param0 
 * @returns 
 */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/** For latex */}
        <link
          href="//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css"
          rel="stylesheet"
        />
      </head>
      <body className={`${inter.className}`}>
        <CourseProviderWrapper>
          <ProfProviderWrapper>
            <DegreeProgramProviderWrapper>
              <SessionProviderWrapper>
                <DatabaseProfileProviderWrapper>
                    {children}
                </DatabaseProfileProviderWrapper>
              </SessionProviderWrapper>
            </DegreeProgramProviderWrapper>
          </ProfProviderWrapper>
        </CourseProviderWrapper>
      </body>
    </html>
  );
}
